### ISSUE TITLE
✏️ App Store 심사 Reject 사유 해결하기

### ISSUE THREAD

**Issue by BangDori** [CorTorE/blogging-study#1]
### 내용 (한줄 요약)

앱 스토어 리젝 사유 트러블슈팅에 대한 포스팅입니다

### 예상 독자

- 앱 스토어 리젝 사유의 원인과 해결 방법을 빠르게 알고 싶은 PM 혹은 앱 개발자 (이전: 앱 개발자)

### 블로그 링크

https://bangdori.kr/posts/appstore-review/

**Comment by asuan99** [comment]
리젝 사유에 대한 트러블 슈팅이라고 하셨는데, 문제 상황에 대해 구체적인 상황은 대외비일 수 있어 공개하기 어려운 점 이해할 수 있습니다.

다만, 앱 개발보다 출시에 대한 트러블 슈팅이라 개발과 배포에 초점을 맞춘 앱 개발자들보다 개발의 전과정을 겸하는 PM의 입장에서의 문제인 것처럼 보이고, 개발에 대한 가이드라인의 형태만 주어지는 게, 예상 독자 선정에 오류가 있는 것처럼 보입니다.

**Comment by asuan99** [comment]
독자를 앱 개발자로 유지하고 싶다면, apple 가이드라인 4.8에 해당 하는 예시, 혹은 반례의 상황을 보일 수 있었으면 좋겠습니다.

**Comment by BangDori** [comment]
@asuan99 말씀해주신 것처럼 Guideline 4.8에 대한 구체적인 해결 방법을 알려주는 것이 아닌 단순히 해결 방안에 대해서만 알려주고 있는 것처럼 느껴져 예상 독자가 앱 개발자보다는 PM에 가깝다고 느껴지는 것 같습니다.

리뷰어님이 말씀대로 아래의 내용을 추가하면 어떨까요?

- 가이드라인 4.8를 충족해야 하는 경우
- 가이드라인 4.8을 충족하지 않아도 되는 경우
- 가이드라인 4.8을 어떻게 해결하였는지 (나의 경험)

**Comment by BangDori** [comment]
@asuan99 가이드라인 4.8를 충족해야 하는 경우와 충족하지 않아도 되는 경우 추가하였습니다.

제가 작성한 포스팅은 사실 애플 로그인을 추가하는 방법보다는 앱 스토어 심사 리젝 사유와 어떻게 미리 대비할 수 있을지? 에 가까운 글이라 4.8을 어떻게 해결하였는지는 추가하지 않았습니다.

**Comment by youngsu5582** [comment]
- 처음에 리젝된 이메일을 섬네일로 보여주면 더 흥미를 줄 거 같네용

> - 앱스토어에 앱을 제출할 때 만약 소셜 로그인 서비스가 포함되어 있다면 반드시 애플 로그인을 추가하자!

-> 앱스토어에 앱을 제출 및 소솔 로그인을 포함할 계획이 있다면 미리 애플 로그인을 추가합시다!

와 같은 느낌으로 변경되어도 괜찮을 거 같습니다.
밑에서 설명하는게 먼저 추가해야 플로우가 안꼬인다는 맥락인데 위 내용과 다소 다른거 같아요.
