### ISSUE TITLE
✏️ [Spring Boot] Mockist 안티 패턴에서 벗어난 TDD 도입해보기

### ISSUE THREAD

**Issue by psychology50** [CorTorE/blogging-study#11]
### 내용 (한줄 요약)

Mock 패턴으로 망해버린 나의 소중한 TDD를 되찾기 위한 여정

### 예상 독자

TDD 기초적인 내용을 이해하고 있고, Mock을 사용하지 않고 비즈니스 로직을 테스트할 방법을 찾고 있는 개발자

### 블로그 링크

https://jaeseo0519.tistory.com/435

**Comment by youngsu5582** [comment]
재서님~ 이번에도 좋은글 잘보고 갑니다.

사실 저도 TDD 자체를 안한지 너무 오래됐습니다 ㅋㄱㅋㄱㄲ..
그냥 내가 짜는 코드가 맞나? 를 확인하는 정도에서 테스트를 짜는 선에서 끝냈습니다.

글 적으로 TDD 의 필요성은 잘 드러난거 같아서 좋았습니다.
객체지향과 클린코드 적인 부분에서도 TDD 가 더 느껴진거 같았구용.

사소한 부분이지만

```java

  public DeviceToken register(@NonNull User user, @NonNull String deviceId, @NonNull String deviceName, @NonNull String token) {
      DeviceToken existingDeviceToken = this.getDeviceTokenByToken(token);

```

```java
    ...
    Optional<User> user = userRdbService.readUser(userId); // user not found 예외는 비즈니스 규칙이므로, collection에서 처리한다.
    Optional<DeviceToken> existingDeviceToken = deviceTokenRdbService.readDeviceByToken(deviceToken);

    // 핵심 비즈니스 규칙 실행: 순수한 도메인 로직
    return new DeviceTokenRegisterCollection(existingDeviceToken.orElse(null))
            .register(user.orElse(null), deviceId, deviceName, deviceToken);
}
```

해당 부분에서 `@NonNull` 인데, orElse(null) 을 넣는 이유가 있나요?

추가로, `Optional<User>` 로 하는 부분도 의견이 궁금합니다.

`Not found` 예외를 던지는건 비즈니스의 규칙인거 같은데
userId 가 없는 `비로그인 사용자 or 익명 사용자` 와 같은 존재도 해당 토큰 등록 로직을 사용할 수 있나요?

위 내용이 아니라면 존재하지 않는 사용자가 DeviceTokenRegisterCollection.register 까지 도달하게 하는게 맞는가?
에 대해 궁금함이 생겨서 물어봅니당.

추가로, Mockito 관련 예전에 본 글 있어서 남기고 갑니당.
[서버사이드 테스트 파랑새를 찾아](https://techblog.woowahan.com/14874/)

**Comment by psychology50** [comment]
> 해당 부분에서 `@NonNull` 인데, orElse(null) 을 넣는 이유가 있나요?

이거 제 코드에선 수정했는데, 실수로 블로그 포스트에선 제거를 안 했었네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ  
수정하러 가겠습니다..~  

아니, 근데 진짜 예리하시네. 어케 찾으셨어요 ㄷㄷ  

<br/>

> `Not found` 예외를 던지는건 비즈니스의 규칙인거 같은데 userId 가 없는 `비로그인 사용자 or 익명 사용자` 와 같은 존재도 해당 토큰 등록 로직을 사용할 수 있나요?

이게 실제 제 서비스에서 사용하는 코든데, 서비스 특성 상 비로그인 유저를 허용을 안 하고 있습니다.  
그래서 언제나 사용자 정보가 존재함을 가정하기 때문에 `Not Found` 예외를 발생시키고 있어요. ㅎㅎ  

이건 포스팅 내용에 포함할까 말까 고민하다가, 괜히 이해를 어렵게 할 거 같아서 제외했던 내용이었습니다.  
디바이스 토큰 내용도 되도록 빼고 싶었는데, 이거까지 포함하면 TDD 관점의 내용을 흐릴까봐 우려되어서요. 허허  

개인적으로 여기서 개선할 만한 점은 DB 설계할 때 애그리게이트로 Entity를 나누지 않은 때여서,  
Device Token의 User 참조를 객체가 아닌 값 타입으로 했으면 조회 쿼리 자체를 없앨 수 있지 않았을까란 아쉬움은 있습니다.  

> 추가로, Mockito 관련 예전에 본 글 있어서 남기고 갑니당. [서버사이드 테스트 파랑새를 찾아](https://techblog.woowahan.com/14874/)

요거 예전에 읽어봤었는데, 당시에 너무 어려워서 포기했던 내용이었네요. ㅋㅋㅋㅋㅋㅋㅋ   
알려주셔서 정말 감사드립니다! 꼭 한 번 읽어볼게요 ㅎㅎ 🤗
