### ISSUE TITLE
외부 API 호출을 30% 가량 빠르게(1) - 기본 로직

### ISSUE THREAD

**Issue by youngsu5582** [CorTorE/blogging-study#2]
### 내용 (한줄 요약)

병렬 깃허브 API 를 비동기로 구현하는 첫번째 내용입니다.

### 예상 독자

외부 API 최적화에 관심있는 독자

### 블로그 링크

[외부(깃허브) 호출을 비동기로 30% 가량 빠르게(1) - 기본 로직](https://velog.io/@dragonsu/%EC%99%B8%EB%B6%80-API-%ED%98%B8%EC%B6%9C%EC%9D%84-30-%EA%B0%80%EB%9F%89-%EB%B9%A0%EB%A5%B4%EA%B2%8C1-%EA%B8%B0%EB%B3%B8-%EB%A1%9C%EC%A7%81)

**Comment by BangDori** [comment]
자바를 잘 알지 못함에도 자바 클래스에 대한 간단한 설명을 덧붙여 주셔서 쉽게 이해할 수 있었던 것 같아요.

조금 아쉬운 점은 결론에서 추가해주신 코드 블럭의 시간들이 어떻게 측정된 건지를 모르겠어요. (i am 프론트엔드 개발자)

**Comment by BangDori** [comment]
아 그리고 추가적인 의견이긴한데 제목에서 수치만을 작성해주기 보다는 아래와 같이 어떻게 했는지를 나타내주는게 저는 더 좋은 거 같아요!

- 외부 API 비동기 호출로 성능 30% 개선하기
- 외부 API 동기에서 비동기 호출 방식으로 개선하기

**Comment by asuan99** [comment]
외부 API를 사용할 때 발생하는 문제와 해결 방안에 대해서 단계적으로 구분된 점이 보기 좋았습니다.
여러 환경에서 실험한 결과를 보여주는 걸로 어떤 환경에서 이점을 가질 수 있는 지 확인할 수 있었지만, 표현 방식이 다소 가독성이 떨어지긴 합니다.

글의 전체적인 구성은 좋습니다. 
다만, 결론의 끝맺음이 아쉬움을 보이긴 합니다. 내용의 순서는 독자로 하여금 읽는 어려움이 없겠지만, 
개인적인 의견으로는, "기대했던 수치에 비해서 어떤 차이가 예상된다" 라는 과정이 없었다는 게 아쉽습니다. 

그리고 수치 표현을 할 때 "평균 xx ~ xx" 라는 표현은 혼동을 유발합니다. 이미 대푯값인 평균이라는 지표 뒤에 범위 지표가 나오니 당혹스럽더군요. "평균"을 "일반적으로" 라는 표현으로 바꾸는 건 어떨까요?

글 제일 앞에 TL;DR 도 넣어주세요🙏
