### ISSUE TITLE
✏️ 외부(깃허브) 호출을 비동기로 30% 가량 빠르게(2) - 스레드 튜닝, 측정

### ISSUE THREAD

**Issue by youngsu5582** [CorTorE/blogging-study#3]
### 내용 (한줄 요약)

스레드를 사용해 외부 API 비동기 실행 통한 성능 향상

### 예상 독자

비동기 및 자바에서 스레드 사용법에 관심이 있는 주니어 개발자, 이력서를 보고 관심을 가지고 들어온 개발자

### 블로그 링크

https://velog.io/@dragonsu/%EC%99%B8%EB%B6%80%EA%B9%83%ED%97%88%EB%B8%8C-%ED%98%B8%EC%B6%9C%EC%9D%84-%EB%B9%84%EB%8F%99%EA%B8%B0%EB%A1%9C-30-%EA%B0%80%EB%9F%89-%EB%B9%A0%EB%A5%B4%EA%B2%8C2-%EC%8A%A4%EB%A0%88%EB%93%9C-%ED%8A%9C%EB%8B%9D-%EC%B8%A1%EC%A0%95

**Comment by asuan99** [comment]
글 잘 읽었습니다. 이전 글과 이어서 글을 작성함에 있어서 생략된 부분이 다소 발생한 것 같네요.
ForkJoinPool 이외에도 다른 대체제가 있는 지 thread pool의 크기에 대한 부분은 어떤 고려가 있는 지에 대해서 면밀히 작성해주셨는데, 실험 과정에서 통제 요인에 대해 명확히 작성해주셔서 실험 과정을 이해하기 수월했습니다.

다만 결론이 다소 급작스럽게 맺어진 것 같습니다. thread 개수를 어떻게 조절할 것인가? 하는 물음에 대해 고려 해야 할 요소들이 다소 그림 한 장을 통해서만 확인할 수 있고, 다른 내용에서는 찾아보기 힘들어 "왜 이걸 고려해야 하는 거지...?" 라는 의문이 생기네요.

**Comment by asuan99** [comment]
Java의 ForkJoinPool이 실질적 동작 과정이 어떤 지는 모르겠지만, C/C++에도 유사하게 thread를 통해 thread pool을 구성해 사용하는 방식이 있습니다. 

명시적으로 thread의 개수를 조정하는 게 성능 향상에 영향을 미치지만, 하드웨어가 수용할 수 있는 스레드 개수를 넘어서는 스레드 개수의 증가는 소프트웨어 레벨에서 개발자가 조정한 임의의 값으로 보일 수 있지만, 하드웨어 레벨에서 실질적으로 동작하는 스레드의 수가 동일하기 때문에, 성능의 차이를 보이기 어렵다고 알고 있습니다.

아마 Java의 ForkJoinPool도 동일한 방식을 취하기 때문에, @youngsu5582 이 처음에 수행한 ForkJoinPool 개수에 대한 실험에서 실행시간 차이가 크게 발생하지 않은 것 같습니다. 

비동기 작업은 서버에 있어 중요한 부분으로 알고 있습니다. 이를 위해 동시성과 병렬성에 대해 추가적으로 학습해보는 건 어떨까요?

**Comment by BangDori** [comment]
@youngsu5582 

> Runtime.getRuntime().availableProcessors();  
> ForkJoinPool.commonPool().getParallelism();
>
> 두개를 출력하면 8개, 7개가 나옵니다.

코드를 작성하고 결과값을 아래에 작성하게 되면 다시 위로 올라가서 읽게 되는 경우가 간혹 있었어서, 아래처럼 코드 옆에 간단한 주석을 하나 추가해주는게 글을 순조롭게 읽는데 도움을 줄 것 같아요.

```js
console.log(a + b); // 15
```

그리고 원호님이 앞서 말씀해주신 것처럼 글이 본격적으로 시작되는 `ThreadPoolExecutor` 부분부터는 이야기보다는 간단한 설명들과 코드만 나오다가 결론이 도출된 것 같아서 화자가 말하고자 하는 바가 단번에 파악하기 힘든 부분도 있는 거 같아요.
